# Generated by Django 5.2.6 on 2025-09-03 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('pres_id', models.AutoField(db_column='pres_ID', primary_key=True, serialize=False)),
                ('pres_nombre', models.CharField(max_length=45)),
                ('tipo_prestamo', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
            },
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('tipr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipr_nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Categoría',
                'verbose_name_plural': 'Tipos de Categoría',
                'db_table': 'tipo_categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=45)),
                ('prod_modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_foto', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_valor_unitario', models.CharField(max_length=45)),
                ('tipo_prestamos', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_cantidad_disponible', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_cantidad_prestada', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_cantidad_total', models.CharField(blank=True, max_length=45, null=True)),
                ('marca', models.ForeignKey(db_column='marca_marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.marca')),
                ('prestamo', models.ForeignKey(db_column='prestamo_pres_ID', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.prestamo')),
                ('tipo_categoria', models.ForeignKey(db_column='tipo_categoria_tipr_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.tipocategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
