# Generated by Django 5.2.6 on 2025-09-20 20:34

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_foto',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.producto_foto_upload_to),
        ),
    ]
