# Generated by Django 5.2.6 on 2025-09-03 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_total', models.CharField(max_length=45)),
                ('cost_partes_afectadas', models.CharField(blank=True, max_length=45, null=True)),
                ('cost_fecha_pago', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'db_table': 'costo',
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('tima_id', models.AutoField(primary_key=True, serialize=False)),
                ('tima_nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de mantenimiento',
                'verbose_name_plural': 'Tipos de mantenimiento',
                'db_table': 'tipo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('mant_id', models.AutoField(primary_key=True, serialize=False)),
                ('mant_fecha', models.CharField(blank=True, max_length=45, null=True)),
                ('mant_descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('costo', models.ForeignKey(db_column='costo_cost_id', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.costo')),
                ('producto', models.ForeignKey(db_column='productos_prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(db_column='Usuario_usua_id', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to=settings.AUTH_USER_MODEL)),
                ('tipo_mantenimiento', models.ForeignKey(db_column='tipo_mantenimiento_tima_id', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
    ]
