# Generated by Django 5.2.6 on 2025-09-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='cost_fecha_pago',
            field=models.DateField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='mant_fecha',
            field=models.DateField(blank=True, max_length=45, null=True),
        ),
    ]
