# Generated by Django 5.2.6 on 2025-09-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('esta_id', models.AutoField(primary_key=True, serialize=False)),
                ('esta_nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('tipa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipa_nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de pago',
                'verbose_name_plural': 'Tipos de pago',
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('renta_fecha_prestamo', models.DateField()),
                ('renta_fecha_devolucion', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
                'db_table': 'Rentas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pago_total_cancelado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pago_fecha_facturacion', models.DateField(blank=True, null=True)),
                ('pago_fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='estado_esta_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='renta.estado')),
                ('renta', models.ForeignKey(db_column='Rentas_rent_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='renta.renta')),
                ('tipo_pago', models.ForeignKey(db_column='tipo_pago_tipa_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='renta.tipopago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
    ]
