# Generated by Django 5.2.6 on 2025-09-03 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(db_column='productos_marca_marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='renta_productos', to='inventario.marca')),
                ('prestamo', models.ForeignKey(db_column='productos_prestamo_pres_ID', on_delete=django.db.models.deletion.PROTECT, related_name='renta_productos', to='inventario.prestamo')),
                ('producto', models.ForeignKey(db_column='productos_prod_id', on_delete=django.db.models.deletion.CASCADE, related_name='renta_productos', to='inventario.producto')),
                ('renta', models.ForeignKey(db_column='Rentas_rent_id', on_delete=django.db.models.deletion.CASCADE, related_name='renta_productos', to='renta.renta')),
                ('tipo_categoria', models.ForeignKey(db_column='productos_tipo_categoria_tipr_id', on_delete=django.db.models.deletion.PROTECT, related_name='renta_productos', to='inventario.tipocategoria')),
            ],
            options={
                'verbose_name': 'Relación Renta-Producto',
                'verbose_name_plural': 'Relaciones Renta-Producto',
                'db_table': 'Rentas_has_productos',
                'unique_together': {('renta', 'producto')},
            },
        ),
    ]
